# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5EwNXvq8F-6z0qfW8Z6X8u2vINHfJ2D
"""

!pip install yfinance pandas
import yfinance as yf
import pandas as pd
import datetime

import matplotlib.pyplot as plt
start_date="2010-01-25"
end_date=datetime.datetime.now()

data_yahoo = yf.download("AMD", start=start_date, end=end_date)
data_yahoo = data_yahoo.reset_index()

data_yahoo.head()
fichier_csv = "/content/AMD.csv"
data_yahoo.to_csv(fichier_csv, index=False)

print(f"\n✅ Fichier CSV créé avec succès : {fichier_csv}")